### ISSUE TITLE
There are several errors when compiling

### ISSUE THREAD

**Issue by mimocu** [EurekaCommunity/TableRow#2]
Hello, there are several errors when compiling and the code is broken, will it be updated?

**Comment by loromits** [comment]
Thanks for bringing attention! Just updated the code, please check 0.3.1

**Comment by mimocu** [comment]
> Gracias por llamar a la atención! Acabo de actualizar el código, por favor verifique 0.3.1.

**Comment by mimocu** [comment]
now it works fine, thanks
