### ISSUE TITLE
InlineTableRow<RowType || CellType>

### ISSUE THREAD

**Issue by AmitaiB** [EurekaCommunity/TableRow#3]
I would love to see an InlineTableRow that can contain other Eureka rows or at least cell types. How difficult would that be? If it's too much bother, I am more than willing to contribute, if you can give me some guidance.

ty

**Comment by loromits** [comment]
First of all, sorry, somehow missed notification on e-mail.
Second, I don't understand the purpose. If you want different row, you can inherit `Eureka.InlineRow`, or even build universal solution to accept any row. Or am I missing the point of customization you want?
